const data = {
  products: [
    {
      name: "free shirt",
      category: "shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInstock: 20,
      description: "A popular shirt",
    },
    {
      name: "fit shirt",
      category: "shirts",
      image: "/images/shirt2.jpg",
      price: 70,
      brand: "adidas",
      rating: 4.5,
      numReviews: 10,
      countInstock: 20,
      description: "A popular shirt",
    },
    {
      name: "slim shirt",
      category: "shirts",
      image: "/images/shirt3.jpg",
      price: 70,
      brand: "raymond",
      rating: 4.5,
      numReviews: 10,
      countInstock: 20,
      description: "A popular shirt",
    },
    {
      name: "golf pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInstock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Pants",
      category: "shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInstock: 20,
      description: "A popular shirt",
    },
    {
      name: "free shirt",
      category: "shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInstock: 20,
      description: "A popular shirt",
    },
  ],
};

export default data;
